# Generated by Django 5.2 on 2025-06-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('app_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_type', models.CharField(max_length=50)),
                ('current_rank', models.IntegerField()),
                ('previous_rank', models.IntegerField()),
                ('trend_score', models.FloatField()),
                ('snapshot_time', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField()),
                ('ratings', models.IntegerField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='dashboard.app')),
            ],
        ),
        migrations.CreateModel(
            name='SentimentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_pct', models.FloatField()),
                ('neutral_pct', models.FloatField()),
                ('negative_pct', models.FloatField()),
                ('keywords', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.app')),
            ],
        ),
    ]
