# Generated by Django 5.2 on 2025-06-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='description',
        ),
    ]
